import type { PlaceRecommendation } from "../shared/places";

export const mockPlaces: PlaceRecommendation[] = [
  {
    id: "mock-atlas",
    name: "Atlas",
    address: "Parkview Square, 600 North Bridge Rd, Singapore",
    rating: 4.6,
    userRatingCount: 2900,
    priceLevel: "PRICE_LEVEL_EXPENSIVE",
    mapsUri: "https://www.google.com/maps/search/?api=1&query=Atlas%20Singapore",
    websiteUri: "https://atlasbar.sg/",
    types: ["bar", "cocktail_bar"],
    isOpenTonight: null,
    statusLabel: "营业时间需确认",
    source: "mock",
    moodTags: ["luxury", "classic", "romantic"]
  },
  {
    id: "mock-jigger",
    name: "Jigger & Pony",
    address: "165 Tanjong Pagar Rd, Singapore",
    rating: 4.7,
    userRatingCount: 2200,
    priceLevel: "PRICE_LEVEL_EXPENSIVE",
    mapsUri: "https://www.google.com/maps/search/?api=1&query=Jigger%20%26%20Pony%20Singapore",
    websiteUri: "https://www.jiggerandpony.com/",
    types: ["bar", "cocktail_bar"],
    isOpenTonight: null,
    statusLabel: "营业时间需确认",
    source: "mock",
    moodTags: ["classic", "social", "luxury"]
  },
  {
    id: "mock-native",
    name: "Native",
    address: "52A Amoy St, Singapore",
    rating: 4.5,
    userRatingCount: 900,
    priceLevel: "PRICE_LEVEL_EXPENSIVE",
    mapsUri: "https://www.google.com/maps/search/?api=1&query=Native%20Singapore%20bar",
    websiteUri: "https://tribenative.com/",
    types: ["bar", "cocktail_bar"],
    isOpenTonight: null,
    statusLabel: "营业时间需确认",
    source: "mock",
    moodTags: ["experimental", "mysterious"]
  },
  {
    id: "mock-manhattan",
    name: "Manhattan",
    address: "Conrad Singapore Orchard, 1 Cuscaden Rd, Singapore",
    rating: 4.6,
    userRatingCount: 1500,
    priceLevel: "PRICE_LEVEL_EXPENSIVE",
    mapsUri: "https://www.google.com/maps/search/?api=1&query=Manhattan%20Bar%20Singapore",
    websiteUri: "https://www.hilton.com/en/hotels/sinodci-conrad-singapore-orchard/dining/manhattan/",
    types: ["bar", "cocktail_bar"],
    isOpenTonight: null,
    statusLabel: "营业时间需确认",
    source: "mock",
    moodTags: ["classic", "luxury", "quiet"]
  },
  {
    id: "mock-mr-stork",
    name: "Mr Stork",
    address: "Andaz Singapore, 5 Fraser St, Singapore",
    rating: 4.3,
    userRatingCount: 1600,
    priceLevel: "PRICE_LEVEL_EXPENSIVE",
    mapsUri: "https://www.google.com/maps/search/?api=1&query=Mr%20Stork%20Singapore",
    websiteUri: "https://www.hyatt.com/andaz/sinaz-andaz-singapore/dining/mr-stork",
    types: ["bar", "rooftop_bar"],
    isOpenTonight: null,
    statusLabel: "营业时间需确认",
    source: "mock",
    moodTags: ["rooftop", "romantic", "social"]
  },
  {
    id: "mock-cool-cats",
    name: "Cool Cats",
    address: "32 Beach Rd, Singapore",
    rating: 4.6,
    userRatingCount: 700,
    priceLevel: "PRICE_LEVEL_EXPENSIVE",
    mapsUri: "https://www.google.com/maps/search/?api=1&query=Cool%20Cats%20Singapore",
    websiteUri: "https://www.coolcats.sg/",
    types: ["bar", "live_music_venue"],
    isOpenTonight: null,
    statusLabel: "营业时间需确认",
    source: "mock",
    moodTags: ["music", "romantic", "luxury"]
  },
  {
    id: "mock-28hks",
    name: "28 HongKong Street",
    address: "28 Hongkong St, Singapore",
    rating: 4.5,
    userRatingCount: 1200,
    priceLevel: "PRICE_LEVEL_EXPENSIVE",
    mapsUri: "https://www.google.com/maps/search/?api=1&query=28%20HongKong%20Street%20Singapore",
    websiteUri: "https://www.28hks.com/",
    types: ["bar", "cocktail_bar"],
    isOpenTonight: null,
    statusLabel: "营业时间需确认",
    source: "mock",
    moodTags: ["mysterious", "classic", "social"]
  },
  {
    id: "mock-offtrack",
    name: "Offtrack",
    address: "34 North Canal Rd, Singapore",
    rating: 4.5,
    userRatingCount: 650,
    priceLevel: "PRICE_LEVEL_MODERATE",
    mapsUri: "https://www.google.com/maps/search/?api=1&query=Offtrack%20Singapore",
    websiteUri: "https://offtrack.sg/",
    types: ["bar", "restaurant"],
    isOpenTonight: null,
    statusLabel: "营业时间需确认",
    source: "mock",
    moodTags: ["music", "quiet", "wildcard"]
  }
];
